#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import Flask, make_response, request, render_template, jsonify
from pyRRD_Redis import RRD_redis
import datetime
from io import BytesIO
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure

app = Flask(__name__)


@app.route("/")
def root():
    tags = RRD_redis('').ls()
    return render_template('rrd_list.html', tags=tags)


@app.route("/view/chart")
def view_chart():
    tag = request.args.get('tag', '', type=str)
    return render_template('view_chart.html', tag=tag)


@app.route("/charts/tag/<string:tag_name>/1.png")
def plot(tag_name):
    # URL params
    nb = int(request.args.get('nb', 0))
    # live PNG generator
    rrd = RRD_redis(tag_name)
    fig = Figure()
    ax = fig.add_subplot(111)
    x = []
    y = []
    for rrv in rrd.get(size=nb):
        x.append(datetime.datetime.fromtimestamp(rrv.timestamp))
        y.append(rrv.value)
    ax.plot_date(x, y, '-', label=tag_name)
    # ax.legend()
    fig.autofmt_xdate()
    canvas = FigureCanvas(fig)
    png_output = BytesIO()
    canvas.print_png(png_output)
    response = make_response(png_output.getvalue())
    response.headers['Content-Type'] = 'image/png'
    return response


@app.route("/api/get")
def get():
    tag_name = request.args.get('tag', '', type=str)
    v = RRD_redis(tag_name).get(size=1)[0]
    return jsonify(value=v.value, timestamp=v.timestamp, time_str=v.time_str)


if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True)
