#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# command line utility for add value to RRD

import argparse
import time
from pyRRD_Redis import RRD_redis

# parse args
parser = argparse.ArgumentParser()
parser.add_argument('tag_name', type=str, help='tag name like L1_M_WOBBE')
parser.add_argument('tag_value', type=float, help='tag value like 12455.0')
parser.add_argument('-t', '--time', type=float,
                    help='timestamp in second for value (default is python time.time())', default=time.time())
args = parser.parse_args()

# add value to RRD
rrd = RRD_redis(args.tag_name)
rrd.add(args.tag_value, at_time=args.time)
