#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# command line utility for remove value from RRD list

import argparse
from pyRRD_Redis import RRD_redis

# parse args
parser = argparse.ArgumentParser()
parser.add_argument('tag_name', type=str, help='tag name like L1_M_WOBBE')
args = parser.parse_args()

rrd = RRD_redis(args.tag_name)
rrd.rm()
