#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# list all rrd tag available on redis server

from redis import StrictRedis

client = StrictRedis()
l_rrd = client.keys('rrd:*')

for tag in l_rrd:
    print(tag.decode('utf-8')[4:])
