#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# command line utility for remove value from RRD list

import argparse
from redis import StrictRedis

# parse args
parser = argparse.ArgumentParser()
parser.add_argument('tag_name', type=str, help='tag name like L1_M_WOBBE')
args = parser.parse_args()

client = StrictRedis()
client.delete('rrd:' + args.tag_name)
